name: Build Test and Publish Nightly Packages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - nightly

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.whichver.outputs.branch }}
    steps:
    - uses: actions/checkout@v2

    - name: Determine package version
      shell: bash
      run: |
        branch=${GITHUB_REF#refs/heads/}
        echo ::set-output name=branch::"${branch}"
      id: whichver


  build-centos-8:
    runs-on: ubuntu-latest
    needs: prep

    steps:
    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/centos-8@centos-debug
      env:
        SRC_REF: "${{ needs.prep.outputs.branch }}"
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-centos-8
        path: artifacts/centos-8



  test-centos-8:
    needs: [build-centos-8]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-8
        path: artifacts/centos-8

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/centos-8@master
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"
        # edb test with -j higher than 1 seems to result in workflow
        # jobs getting killed arbitrarily by Github.
        PKG_TEST_JOBS: 1




  publish-centos-8:
    needs: [test-centos-8]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-8
        path: artifacts/centos-8

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: centos-8

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/centos-8@master
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/centos-8@master
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"
        PKG_INSTALL_REF: "${{ steps.describe.outputs.install-ref }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
